#!/bin/sh
# Nodeの環境を設定
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

# .nvmrcがあれば、適切なNodeバージョンを使用
if [ -f ".nvmrc" ]; then
  nvm use
fi

echo "🔍 通常のリンクチェックを実行中..."
npm run check-links

# 通常のリンクチェックが失敗した場合
if [ $? -ne 0 ]; then
  echo "❌ リンクチェックに失敗しました。コミットを中止します。"
  echo "修正してから再度コミットしてください。"
  exit 1
fi

echo "✅ リンクチェックに成功しました。"

echo "🔍 ステージングされたファイルにフォーマットを適用中..."
# ステージングされたファイルを変数に保存
STAGED_FILES_PRETTIER=$(git diff --cached --name-only --diff-filter=ACMR | grep -E '\.(js|jsx|ts|tsx|json|md|css|svg)$')

if [ -n "$STAGED_FILES_PRETTIER" ]; then
  # Prettierでフォーマットを適用
  npx prettier --write $STAGED_FILES_PRETTIER
  
  # フォーマットしたファイルを再度ステージングに追加
  echo "🔄 フォーマットされたファイルを再ステージング中..."
  git add $STAGED_FILES_PRETTIER
fi

echo "🔍 ステージングされたファイルのESLintエラーをチェック中（警告は無視）..."
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACMR | grep -E '\.(js|jsx|ts|tsx)$')
if [ -n "$STAGED_FILES" ]; then
  # ESLintでエラーを修正（--fixオプションを使用）
  npx eslint --quiet --fix $STAGED_FILES
  
  # ESLintで修正したファイルを再度ステージングに追加
  echo "🔄 ESLintで修正されたファイルを再ステージング中..."
  git add $STAGED_FILES
  
  # 修正後に再度ESLintでチェックし、解決できなかったエラーがあればコミットを中止
  npx eslint --quiet $STAGED_FILES
  
  # エラーがある場合のみコミットを中止
  if [ $? -ne 0 ]; then
    echo "❌ ESLintのエラーが見つかりました。コミットを中止します。"
    echo "エラーを修正してから再度コミットしてください。"
    exit 1
  fi
fi

echo "✅ コード整形とESLintエラーチェックに成功しました。"